name: Deploy AWS Lambda
on:
    push:
      branches:
        - main
      paths:
        - 'lambda/'
jobs:
  deploy-lambda: # name of the job
    runs-on: ubuntu-latest # sets or specifies the type of runner to use
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python # Sets up the Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies # Installs any packages
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS credentials # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deployment Success # displays a message if deployment is successful
        if: success()
        run: echo "Lambda function deployed successfully!"

      - name: Deployment Failed # displays a message if deployment fails
        if: failure()
        run: echo "Lambda deployment failed!" && exit 1
